package club.pisquad.uiharu.qqbot.websocket.schemas

import kotlinx.serialization.Serializable

@Serializable
enum class OpCode(val value: Int) {
    DISPATCH(0),
    HEARTBEAT(1),
    IDENTIFY(2),
    RESUME(6),
    RECONNECT(7),
    INVALID_SESSION(9),
    HELLO(10),
    HEARTBEAT_ACK(11),
    HTTP_CALLBACK_ACK(12);

    override fun toString(): String {
        return ordinal.toString()
    }

    companion object {
        fun valueOf(value: Int) = entries.find { it.value == value }
    }
}

enum class EventType(val value: String) {
    GUILD_CREATE("GUILD_CREATE"),
    GUILD_UPDATE("GUILD_UPDATE"),
    GUILD_DELETE("GUILD_DELETE"),
    CHANNEL_CREATE("CHANNEL_CREATE"),
    CHANNEL_UPDATE("CHANNEL_UPDATE"),
    CHANNEL_DELETE("CHANNEL_DELETE"),
    GUILD_MEMBER_ADD("GUILD_MEMBER_ADD"),
    GUILD_MEMBER_UPDATE("GUILD_MEMBER_UPDATE"),
    GUILD_MEMBER_REMOVE("GUILD_MEMBER_REMOVE"),
    MESSAGE_CREATE("MESSAGE_CREATE"),
    MESSAGE_REACTION_ADD("MESSAGE_REACTION_ADD"),
    MESSAGE_REACTION_REMOVE("MESSAGE_REACTION_REMOVE"),
    AT_MESSAGE_CREATE("AT_MESSAGE_CREATE"),
    PUBLIC_MESSAGE_DELETE("PUBLIC_MESSAGE_DELETE"),
    DIRECT_MESSAGE_CREATE("DIRECT_MESSAGE_CREATE"),
    DIRECT_MESSAGE_DELETE("DIRECT_MESSAGE_DELETE"),
    AUDIO_START("AUDIO_START"),
    AUDIO_FINISH("AUDIO_FINISH"),
    AUDIO_ON_MIC("AUDIO_ON_MIC"),
    AUDIO_OFF_MIC("AUDIO_OFF_MIC"),
    MESSAGE_AUDIT_PASS("MESSAGE_AUDIT_PASS"),
    MESSAGE_AUDIT_REJECT("MESSAGE_AUDIT_REJECT"),
    MESSAGE_DELETE("MESSAGE_DELETE"),
    FORUM_THREAD_CREATE("FORUM_THREAD_CREATE"),
    FORUM_THREAD_UPDATE("FORUM_THREAD_UPDATE"),
    FORUM_THREAD_DELETE("FORUM_THREAD_DELETE"),
    FORUM_POST_CREATE("FORUM_POST_CREATE"),
    FORUM_POST_DELETE("FORUM_POST_DELETE"),
    FORUM_REPLY_CREATE("FORUM_REPLY_CREATE"),
    FORUM_REPLY_DELETE("FORUM_REPLY_DELETE"),
    FORUM_PUBLISH_AUDIT_RESULT("FORUM_PUBLISH_AUDIT_RESULT"),
    INTERACTION_CREATE("INTERACTION_CREATE"),
}

@Serializable
data class PayloadBase<T>(
    //TODO: use enum class in here
    val op: Int,
    val d: T? = null,
    val s: Int? = null,
    val t: String = "",
)